version: '3'
services:
  movie-app:
    image: movie-app
    network_mode: host
    build: ServerApi/
    restart: always
    container_name: spring-docker
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    expose:
      - 8080
  user-auth-app:
    image: user-auth-app
    build: SSOAuthApi/
    network_mode: host
    container_name: auth-docker
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "8089:8089"
    expose:
      - 8089
  angular-app:
    image: angular-app
    build: FrontendApi/
    network_mode: host
    restart: always
    container_name: angular-docker
    ports:
      - "4200:4200"
    expose:
      - 4200

  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    network_mode: host
    environment:
      MYSQL_DATABASE: moviedb
      MYSQL_USER: root-app
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root